### ISSUE TITLE
Rakefile does not build

### ISSUE THREAD

**Issue by wrq** [grosser/dispel#2]
When I clone and Rake, I get error about bump/tasks not being found.
Commenting that out, I get errors about ripper, which doesn't seem to support anything past 1.8.7

I am curious to get this thing building, because I'd like to dig in and add some features to it, since this hasn't been touched for almost 2 years.

**Comment by grosser** [comment]
only works on 2.0.0

**Comment by grosser** [comment]
`bundle exec`

**Comment by grosser** [comment]
rebased and updated a bit
