### ISSUE TITLE
Release new Gem on RubyGems

### ISSUE THREAD

**Issue by yorickpeterse** [grosser/dispel#5]
@grosser Would it be possible to push a new version of the Gem to RubyGems? The `master` branch contains a few changes that are not available on RubyGems, and we (GitLab) would like to be able to make use of those changes, without having to use a `git` source in Bundler.

**Comment by YorickPeterse** [comment]
@grosser Thanks! It is open source (https://gitlab.com/gitlab-org/takeoff), though not terribly useful since it's specifically meant for how we currently do deploys at GitLab. We currently use dispel for a command to obtain some statistics about our HAProxy load balancers.

**Comment by grosser** [comment]
FYI keys are symbols, so this looks wrong:
`    elsif key == :"Ctrl+q" || key == "Ctrl+c"`
